workspace:
  base: /go
  path: src/g.ls42.de/stephan/penunse
  
pipeline:
  backend:
    image: golang:latest
    commands:
      - go get
      - go get github.com/boltdb/bolt
      - go get golang.org/x/crypto/bcrypt
      - go get github.com/jinzhu/gorm
      - go get github.com/qor/auth
      - go get github.com/qor/session
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet $(go list ./... | grep -v /vendor/)
      - go test $(go list ./... | grep -v /vendor/)

  # frontend:
    # image: node:latest
    # commands:
      # - npm install
      # - npm run lint
      # - npm run test
# 