image: golang:latest

variables:
  REPO_NAME: gitlab.ls42.de/go/penunse

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - go get github.com/boltdb/bolt


stages:
  - test
  - build

test:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test $(go list ./... | grep -v /vendor/)

build:
  stage: build
  script:
    - CGO_ENABLED=0 GOOS=linux go build -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/penunse
# This is how I build automated releases
#  artifacts:
#    paths:
#      - penunse
